#!/bin/bash
# Simple shell script to run application in dev mode
python manage.py runserver --settings=Pastebin.settings.development
python manage.py createsuperuser --settings=Pastebin.settings.development
python manage.py makemigrations --settings=Pastebin.settings.development
python manage.py migrate --settings=Pastebin.settings.development
python manage.py showmigrations --settings=Pastebin.settings.development
python manage.py migrate --fake app zero --settings=Pastebin.settings.development
python manage.py collectstatic --help --settings=Pastebin.settings.development