# Generated by Django 2.2 on 2019-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190601_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
